version: "1.0"

services:
  postgres:
    container_name: postgres-loja-central
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adm123
      - POSTGRES_DB=lojacentral
    ports:
      - 5432:5432
    volumes:
      - /media/guilherme/ArquivosLinux/pgdatacentral:/var/lib/postgresql/data

  api-python:
    restart: always
    build:
      context: ../
      dockerfile: docker/DockerfilePython
    ports:
      - 5000:5000
    depends_on:
      - postgres

  redis:
    restart: always
    build:
      context: ../
      dockerfile: docker/DockerfileRedis
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /media/guilherme/ArquivosLinux/redisdata:/data
    depends_on:
      - postgres
      - api-python

  api-java:
    restart: always
    build:
      context: ../
      dockerfile: docker/DockerfileJava
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lojacentral?useTimezone=true&serverTimeZone=America/Sao_Paulo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=adm123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_EXPIRATION=900000
      - JWT_REFRESH_EXPIRATION=2592000000
    depends_on:
      - postgres
      - api-python
      - redis

  lojacentral_frontend:
    container_name: lojacentral-frontend
    restart: always
    build:
      context: ..
      dockerfile: docker/DockerfileFront
    ports:
      - 4300:4300
    stdin_open: true
    depends_on:
      - postgres
      - api-python
      - api-java
      - redis
