# DataSource Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lojacentral?useTimezone=true&serverTimeZone=America/Sao_Paulo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:adm123}
    # url: jdbc:postgresql://localhost:5432/lojacentral?useTimezone=true&serverTimeZone=America/Sao_Paulo
    # # url: jdbc:postgresql://postgres:5432/lojacentral?useTimezone=true&serverTimeZone=America/Sao_Paulo
    # username: postgres
    # password: adm123

  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
        show_sql: false
    show-sql: false

  # Jackson
  jackson:
    time-zone: America/Sao_Paulo

  # SQL Initialization Configuration
  sql:
    init:
      mode: always
      platform: postgresql

  # swagger-ui custom path
  swagger-ui:
    path: /swagger-ui.html
    clientId: "153"
    clientSecret: "123123"
# Server Configuration
server:
  port: 8080

# API Security Configuration
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
